

services:
  web:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000" 
    working_dir: /app     
    environment:
      - NODE_ENV=development
      - PORT=3000
      - WATCHPACK_POLLING=true
    command: npm run dev
